#!/usr/bin/env perl
# vim:syntax=perl

die "Need Container Name" if scalar(@ARGV)<1;
$container = $ARGV[0];
$cmd = "docker container stop $container && docker container rm $container";
print "Execute: $cmd\n";
`$cmd`;
